let cached = null;

const DOM_IDS = [
  ['editor', 'editor'],
  ['tabsList', 'tabs-list'],
  ['newTabBtn', 'new-tab-btn'],
  ['newFileBtn', 'new-file-btn'],
  ['chatBtn', 'chat-btn'],
  ['closeChatBtn', 'close-chat-btn'],
  ['clearChatBtn', 'clear-chat-btn'],
  ['chatPanel', 'chat-panel'],
  ['chatMessages', 'chat-messages'],
  ['chatStatus', 'chat-status'],
  ['userInput', 'user-input'],
  ['sendBtn', 'send-btn'],
  ['stopBtn', 'stop-btn'],
  ['settingsBtn', 'open-settings-btn'],
  ['settingsModal', 'modal-settings'],
  ['closeSettingsBtn', 'close-settings'],
  ['closeSettingsBtn2', 'close-settings-btn'],
  ['fontSizeSelect', 'font-size-select'],
  ['themeSelect', 'theme-select'],
  ['tabSizeSelect', 'tab-size-select'],
  ['lineNumbers', 'line-numbers'],
  ['glassOpacityRange', 'glass-opacity-range'],
  ['glassOpacityValue', 'glass-opacity-value'],
  ['glassBlurRange', 'glass-blur-range'],
  ['glassBlurValue', 'glass-blur-value'],
  ['glassEnabledCheckbox', 'glass-enabled-checkbox'],
  ['autoScaleCheckbox', 'auto-scale-checkbox'],
  ['wordWrapCheckbox', 'word-wrap-checkbox'],
  ['lineNumbersCheckbox', 'line-numbers-checkbox'],
  ['zoomValueEl', 'zoom-value'],
  ['zoomInBtn', 'zoom-in-btn'],
  ['zoomOutBtn', 'zoom-out-btn'],
  ['zoomResetBtn', 'zoom-reset-btn'],
  ['statusFile', 'status-file'],
  ['statusCursor', 'status-cursor'],
  ['statusZoom', 'status-zoom'],
  ['statusLang', 'status-lang'],
  ['accentColorSelect', 'accent-color-select'],
  ['uiRadiusRange', 'ui-radius-range'],
  ['uiRadiusValue', 'ui-radius-value'],
  ['uiGapRange', 'ui-gap-range'],
  ['uiGapValue', 'ui-gap-value'],
  ['compactUiCheckbox', 'compact-ui-checkbox'],
  ['glassRimRange', 'glass-rim-range'],
  ['glassRimValue', 'glass-rim-value'],
  ['glassShadowRange', 'glass-shadow-range'],
  ['glassShadowValue', 'glass-shadow-value'],
  ['editorDimRange', 'editor-dim-range'],
  ['editorDimValue', 'editor-dim-value'],
  ['terminalHeightRange', 'terminal-height-range'],
  ['terminalHeightValue', 'terminal-height-value'],
  ['terminalBtn', 'terminal-btn'],
  ['terminalPanel', 'terminal-panel'],
  ['terminalXtermHost', 'terminal-xterm'],
  ['terminalMeta', 'terminal-meta'],
  ['terminalClearBtn', 'terminal-clear-btn'],
  ['terminalRestartBtn', 'terminal-restart-btn'],
  ['terminalCloseBtn', 'terminal-close-btn'],
  ['terminalResizeHandle', 'terminal-resize'],
  ['statusTerminalBtn', 'status-terminal-btn'],
  ['welcomePage', 'welcome-page'],
  ['editorTabs', 'editor-tabs'],
  ['editorContainer', 'editor-container'],
  ['showWelcomeCheckbox', 'show-welcome-checkbox'],
  ['newFileAction', 'new-file-action'],
  ['openFileAction', 'open-file-action'],
  ['aiChatAction', 'ai-chat-action'],
  ['aiProviderSelect', 'ai-provider-select'],
  ['aiModelSelect', 'ai-model-select'],
  ['openRouterKeyInput', 'openrouter-key'],
  ['saveOpenRouterKeyBtn', 'save-openrouter-key'],
  ['openRouterStatus', 'openrouter-status'],
  ['defaultAiProviderSelect', 'default-ai-provider'],
  ['openRouterSection', 'openrouter-section'],
  ['ollamaSection', 'ollama-section'],
  ['explorerBtn', 'explorer-btn'],
  ['searchBtn', 'search-btn'],
  ['gitBtn', 'git-btn'],
  ['debugBtn', 'debug-btn'],
  ['activityPanel', 'activity-panel'],
  ['appBgColor', 'app-bg-color'],
  ['sidebarBgColor', 'sidebar-bg-color'],
  ['editorBgColor', 'editor-bg-color'],
  ['panelBgColor', 'panel-bg-color'],
  ['appOpacityRange', 'app-opacity-range'],
  ['appOpacityValue', 'app-opacity-value'],
  ['sidebarOpacityRange', 'sidebar-opacity-range'],
  ['sidebarOpacityValue', 'sidebar-opacity-value'],
  ['activityOpacityRange', 'activity-opacity-range'],
  ['activityOpacityValue', 'activity-opacity-value'],
  ['editorSurfaceOpacityRange', 'editor-surface-opacity-range'],
  ['editorSurfaceOpacityValue', 'editor-surface-opacity-value'],
  ['terminalOpacityRange', 'terminal-opacity-range'],
  ['terminalOpacityValue', 'terminal-opacity-value'],
  ['bgImageUrlInput', 'bg-image-url'],
  ['bgImageOpacityRange', 'bg-image-opacity-range'],
  ['bgImageOpacityValue', 'bg-image-opacity-value'],
];

export function getDom() {
  if (cached) return cached;
  const dom = {
    glassBlurCheckbox: null,
    ambientBgCheckbox: null,
  };
  for (const [key, id] of DOM_IDS) {
    dom[key] = document.getElementById(id);
  }
  dom.glassBlurCheckbox = dom.glassEnabledCheckbox;
  cached = dom;
  return dom;
}

/** Re-query dynamic panels after innerHTML rebuilds */
export function invalidateDomCache() {
  cached = null;
}
