/** Shared mutable renderer state */
export const state = {
  currentTabs: [],
  activeTabIndex: -1,
  chatVisible: false,
  currentActivity: 'explorer',
  activityVisible: true,
  activityWidth: 260,
  currentFolder: null,
  fileExplorerItems: [],
  expandedFolders: new Set(),
  folderChildrenCache: new Map(),
  selectedExplorerPath: null,
  copiedFilePath: null,
  chatHistory: [],
  findBarVisible: false,
  findMatches: [],
  findMatchIndex: -1,
  findCaseSensitive: false,
  editorZoom: 1,
  autoScaleEnabled: true,
  wordWrapEnabled: false,
  autoSave: false,
  glassPreset: /Mac|Win/i.test(navigator.platform) ? 'regular' : 'off',
  glassQuality: 'auto',
  glassOpacity: null,
  glassBlur: null,
  customThemes: [],
  activeTheme: null,
  themeApplied: false,
  editorFont: '',
  uiFont: '',
  fontLigatures: false,
  closedTabs: [],
  agentAccess: 'read',
  agentPaths: { claude: '', codex: '', opencode: '' },
  agentSessions: {},
  live: null,
  lineNumbersEnabled: true,
  accentColor: '#21aabe',
  uiRadius: 12,
  uiGap: 4,
  compactUi: false,
  terminalHeight: 220,
  terminalVisible: false,
  terminalStarted: false,
  terminalInEditor: false,
  xterm: null,
  fitAddon: null,
  splitView: false,
  focusedPane: 'left',
  rightTabIndex: -1,
  glassRim: 10,
  glassShadow: 12,
  editorDim: 0.88,
  appBg: '#16181d',
  sidebarBg: '#1c1f26',
  editorBg: '#1a1d23',
  panelBg: '#1e2229',
  appOpacity: 1,
  sidebarOpacity: 0.78,
  activityOpacity: 0.78,
  editorSurfaceOpacity: 0.78,
  terminalOpacity: 1,
  bgImageUrl: '',
  bgImageOpacity: 0,
  currentAiProvider: 'ollama',
  currentAiModel: 'llama3',
  defaultAiProvider: 'ollama',
  openRouterModels: [],
  openCodeModels: [],
  opencodeBaseUrl: 'http://127.0.0.1:4096',
  isTyping: false,
  contextMenu: null,
};
